Clang tidy Google Style Guide
swift-nav/cmake pull request #155
Opened 2023-06-01 13:28 UTC by RReichert

2023-06-01 13:31 UTC, RReichert commented on ClangTidy.cmake
> +  - { key: readability-identifier-naming.TemplateParameterIgnoredRegexp, value: 'expr-type'}
This needs to be added to avoid a bug in clang-tidy that only has been recently been fixed - https://github.com/llvm/llvm-project/issues/46097

2023-07-15 05:05 UTC, silverjam requested changes
Why are we doing this in CMake when this was already implemented in Bazel?  We have a mandate (from the VP of engineering and the software VP) to migrate to Bazel, implementing new features in CMake takes us farther away from that goal.  CMake should be considered as "maintenance mode" only -- new work in CMake should have a very clear justification why it's not possible in Bazel and DevInfra needs to be made aware so that we can plan to bring Bazel into parity.

2023-07-16 18:00 UTC, silverjam approved these changes

2023-07-17 00:03 UTC, RReichert commented on ClangTidy.cmake
> +  - { key: readability-identifier-naming.EnumConstantCase,               value: UPPER_CASE }
This is an extract from our style guide, I assume that its UPPER_CASE:

![image](https://github.com/swift-nav/cmake/assets/2455904/8d556a5b-8c39-4abc-888a-dbcda4ddee0f)

2023-07-17 00:04 UTC, RReichert commented on ClangTidy.cmake
> +  - { key: readability-identifier-naming.FunctionCase,                   value: lower_case }
Good question, will test it out tomorrow to see if it inherits the behaviour, hopefully it does.

2023-07-17 23:24 UTC, RReichert commented on ClangTidy.cmake
> +  - { key: readability-identifier-naming.FunctionCase,                   value: lower_case }
can confirm that the behaviour gets inherited, so it correctly picks up the various functions types.

2023-07-17 23:36 UTC, RReichert commented on ClangTidy.cmake
> +CheckOptions:
Had a look into this, looks like activating this would error out every header file as the Google Style Guide mandates the format of `<PROJECT>_<PATH>_<FILE>_H_` for the header guides which we follow.

2023-07-18 05:01 UTC, woodfell approved these changes

2023-07-18 05:02 UTC, merged