[ESD-2113] Add license notice
swift-nav/cmake pull request #91
Opened 2021-06-30 07:26 UTC by woodfell

Open source repository license under MIT.

Add `LICENSE` file, a note in `README.md` and a copyright notice at the top of every file.

2021-06-30 08:30 UTC, jayvdb requested changes

2021-06-30 08:30 UTC, jayvdb commented on scripts/parse_stackusage.py
>  #!/usr/bin/env python
hashbangs must be on the first line

2021-06-30 21:28 UTC, silverjam approved these changes

2021-06-30 22:31 UTC, woodfell commented
Thanks @silverjam

2021-06-30 23:00 UTC, RReichert approved these changes

2021-07-01 01:12 UTC, jayvdb approved these changes

2021-07-01 01:18 UTC, merged

2021-07-01 07:00 UTC, weakcamel commented
Fantastic, thank you for adding this.