[ESD-2038] Script to check for misused of __attribute__
swift-nav/cmake pull request #93
Opened 2021-07-19 21:07 UTC by woodfell

The use of plain `__attribute__` is causing some portability issues. https://github.com/swift-nav/libswiftnav-private/pull/274 introduces a header to abstract away attributes behind some preprocessor macros which are protected and redefined by compiler detecting `#if` blocks

This script is a parallel effort to help prevent future erroneous usage of `__attribute__`. This module and script can be used by any project and adds a new target which looks through all source and header files in a repository and flags an IDE parsable error should `__attribute__` be used anywhere. The script is fairly dumb and just greps through all files tracked by git. It's not a perfect solution but will definitely fail CI in the event of a misuse.

This has been demonstrated in other Swift repositories in a series of other PRs

2021-07-19 21:32 UTC, silverjam commented on CheckAttributes.cmake
> +  set(arguments "'*.[ch]'" "'*.[ch]pp'" "'*.cc'")
Should we ".cxx" and ".hxx" too?

2021-07-19 21:35 UTC, silverjam requested changes

2021-07-19 21:35 UTC, silverjam commented on scripts/check_attributes.sh
> +failed=0
Suggest just naming this `status`

2021-07-19 21:37 UTC, silverjam reviewed
Also suggest running this script through shellcheck: https://github.com/koalaman/shellcheck

2021-07-20 00:55 UTC, woodfell commented
Reworked the script to get it passing with `shellcheck` while still not requiring bash

2021-07-20 01:17 UTC, RReichert approved these changes
LGTM, if you can be bothered, a quick doc on the function  would be nice to have

2021-07-21 07:24 UTC, merged